/** TUI 简体中文映射：工具标签页。 */
const strings: Record<string, string> = {
	"group.tools.Available Tools": "可用工具",
	"group.tools.Todos": "Todo",
	"group.tools.Grep & Browser": "Grep 与浏览器",
	"group.tools.Computer": "Computer",
	"group.tools.GitHub": "GitHub",
	"group.tools.Output Limits": "输出限制",
	"group.tools.Execution": "执行",
	"group.tools.Discovery & MCP": "发现与 MCP",
	"group.tools.Extensions": "扩展",
	"group.tools.Developer": "开发者",
	"setting.tools.artifactSpillThreshold.label": "输出物溢出阈值（KB）",
	"setting.tools.artifactSpillThreshold.description": "超过此大小的工具输出将被保存为输出物；保留尾部内联",
	"setting.tools.artifactTailBytes.label": "输出物尾部大小（KB）",
	"setting.tools.artifactTailBytes.description": "输出溢出到输出物时保留的内联尾部内容量",
	"setting.tools.artifactHeadBytes.label": "输出物头部大小（KB）",
	"setting.tools.artifactHeadBytes.description":
		"输出溢出到输出物时保留的内联头部内容量（中间省略）。0 禁用 — 仅保留尾部",
	"setting.tools.outputMaxColumns.label": "输出列上限",
	"setting.tools.outputMaxColumns.description":
		"流式工具输出（bash、python、js eval）和 read 的每行字节上限。超过此宽度的行会被省略截断；剩余字节到下一个换行符被丢弃。0 禁用",
	"setting.tools.artifactTailLines.label": "输出物尾部行数",
	"setting.tools.artifactTailLines.description": "输出溢出到输出物时保留的内联尾部最大行数",
	"setting.todo.enabled.label": "任务清单",
	"setting.todo.enabled.description": "启用 todo 工具进行任务跟踪",
	"setting.todo.reminders.label": "任务清单提醒",
	"setting.todo.reminders.description": "在停止前提醒 agent 完成待办事项",
	"setting.todo.remindersMax.label": "任务清单提醒上限",
	"setting.todo.remindersMax.description": "放弃前最多的任务清单提醒次数",
	"setting.todo.eager.label": "自动创建任务清单",
	"setting.todo.eager.description": "在第一条消息后推动自动创建任务清单的强度",
	"setting.glob.enabled.label": "Glob",
	"setting.glob.enabled.description": "启用 glob 工具进行基于 glob 的文件查找",
	"setting.grep.enabled.label": "Grep",
	"setting.grep.enabled.description": "启用 grep 工具进行正则内容搜索",
	"setting.grep.contextBefore.label": "Grep 上下文前置",
	"setting.grep.contextBefore.description": "每个 grep 匹配前的上下文行数",
	"setting.grep.contextAfter.label": "Grep 上下文后置",
	"setting.grep.contextAfter.description": "每个 grep 匹配后的上下文行数",
	"setting.astGrep.enabled.label": "AST Grep",
	"setting.astGrep.enabled.description": "启用 ast_grep 工具进行结构化 AST 搜索",
	"setting.astEdit.enabled.label": "AST Edit",
	"setting.astEdit.enabled.description": "启用 ast_edit 工具进行结构化 AST 重写",
	"setting.debug.enabled.label": "调试",
	"setting.debug.enabled.description": "启用 debug 工具进行基于 DAP 的调试",
	"setting.launch.enabled.label": "启动",
	"setting.launch.enabled.description": "启用 launch 工具管理共享的长期运行的项目进程",
	"setting.speechgen.enabled.label": "语音生成",
	"setting.speechgen.enabled.description": "启用 tts 工具进行设备端（Kokoro）或 xAI Grok Voice 语音文件合成",
	"setting.generate_image.enabled.label": "生成图片",
	"setting.generate_image.enabled.description":
		"启用 generate_image 工具（文本到图像生成与编辑）。tools.xdev 开启时作为 xd:// 设备暴露",
	"setting.computer.enabled.label": "计算机",
	"setting.computer.enabled.description": "启用脚本化主机-桌面 eval 预lude（截图、输入、无障碍）",
	"setting.computer.display.label": "计算机显示",
	"setting.computer.display.description": "合成所有显示器或选择原生显示 ID",
	"setting.computer.maxWidth.label": "计算机截图宽度",
	"setting.computer.maxWidth.description": "合成截图的最大宽度（像素）",
	"setting.computer.maxHeight.label": "计算机截图高度",
	"setting.computer.maxHeight.description": "合成截图的最大高度（像素）",
	"setting.images.questionTimeoutMs.label": "图片问题超时",
	"setting.images.questionTimeoutMs.description":
		"read 的 ?q= 图片问题后端 vision-model 调用的每次请求超时（毫秒）。停滞的提供程序快速超时而非阻塞直到手动中止。0 禁用",
	"setting.checkpoint.enabled.label": "检查点/回退",
	"setting.checkpoint.enabled.description": "启用 checkpoint 和 rewind 工具进行上下文检查点",
	"setting.fetch.enabled.label": "读取 URL",
	"setting.fetch.enabled.description": "允许 read 工具获取和处理 URL",
	"setting.vault.enabled.label": "Obsidian 知识库",
	"setting.vault.enabled.description": "启用 vault:// 内部 URL 通过 Obsidian CLI 读取和编辑 Obsidian 知识库内容",
	"setting.github.enabled.label": "GitHub CLI",
	"setting.github.enabled.description":
		"启用 github 工具（仓库、issue、PR、diff、搜索、checkout、push、Actions 工作流监控的 op 调度）",
	"setting.github.cache.enabled.label": "GitHub 视图缓存",
	"setting.github.cache.enabled.description":
		"在 ~/.omp/cache/github-cache.db 中缓存渲染后的 issue/PR 视图输出，使重复读取免费",
	"setting.github.cache.softTtlSec.label": "GitHub 缓存软过期",
	"setting.github.cache.softTtlSec.description": "在此窗口内直接返回缓存的 issue/PR 视图行（秒；默认 5 分钟）",
	"setting.github.cache.hardTtlSec.label": "GitHub 缓存硬过期",
	"setting.github.cache.hardTtlSec.description":
		"超过软过期后缓存行被返回并后台刷新；超过硬过期后丢弃（秒；默认 7 天）",
	"setting.web_search.enabled.label": "Web 搜索",
	"setting.web_search.enabled.description": "启用 web_search 工具获取实时 web 结果",
	"setting.security.enabled.label": "安全",
	"setting.security.enabled.description": "启用 OMP 原生安全扫描规划、执行及只读 security:// 资源命名空间",
	"setting.ask.enabled.label": "询问",
	"setting.ask.enabled.description": "启用 ask 工具进行交互式用户提问",
	"setting.browser.enabled.label": "浏览器",
	"setting.browser.enabled.description": "启用 browser 评估预lude 进行脚本化 Chromium 自动化（Puppeteer）",
	"setting.browser.cdpUrl.label": "浏览器 CDP URL",
	"setting.browser.cdpUrl.description": "默认 HTTP CDP 发现端点（如 http://127.0.0.1:9222）用于附加而非启动浏览器",
	"setting.browser.relay.label": "浏览器中继",
	"setting.browser.relay.description":
		"通过 omp 浏览器中继驱动你自己的 Chrome 标签页。安装扩展一次（`omp browser-relay install`）；中继服务器在浏览器预lude 需要时自动启动",
	"setting.browser.relayUrl.label": "浏览器中继 URL",
	"setting.browser.relayUrl.description": "omp 浏览器中继端点（默认 http://127.0.0.1:9224）",
	"setting.browser.headless.label": "无头浏览器",
	"setting.browser.headless.description": "以无头模式启动浏览器（关闭以显示浏览器界面）",
	"setting.browser.cmux.label": "cmux 浏览器",
	"setting.browser.cmux.description": "在有 cmux socket 时使用 cmux WKWebView 表面进行浏览器自动化",
	"setting.browser.screenshotDir.label": "截图目录",
	"setting.browser.screenshotDir.description":
		"保存截图的目录。若未设置，截图进入临时文件。支持 ~。例如：~/Downloads、~/Desktop、/sdcard/Download（Android）",
	"setting.tools.intentTracing.label": "意图追踪",
	"setting.tools.intentTracing.description": "在执工具调用前要求 agent 描述其意图",
	"setting.tools.abortOnFabricatedResult.label": "发现伪造工具结果时中止",
	"setting.tools.abortOnFabricatedResult.description":
		"在内联工具调用中，当模型开始在半途中幻觉工具结果时立即停止模型。禁用让模型生成完毕并丢弃伪造的延续部分",
	"setting.tools.maxTimeout.label": "工具最大超时",
	"setting.tools.maxTimeout.description": "agent 可为任何工具设置的最大超时时间（秒；0 = 无限制）",
	"setting.async.enabled.label": "异步执行",
	"setting.async.enabled.description": "启用异步 bash 命令和后台任务执行",
	"setting.async.pollWaitDuration.label": "最大轮询时间",
	"setting.async.pollWaitDuration.description":
		"hub wait 等待后台任务返回当前状态的最大时间。`smart` 模式自适应：从 5s 开始每次连续等待递增（最高 5m），约一分钟后无等待时重置为 5s",
	"setting.irc.timeoutMs.label": "IRC 超时",
	"setting.irc.timeoutMs.description": "hub 消息等待的默认超时时间（毫秒）；0 禁用超时",
	"setting.tools.xdev.label": "xd:// 工具",
	"setting.tools.xdev.description":
		"在 xd:// 设备 URL 下挂载很少使用的（可发现的）工具，通过 read/write 驱动而非在每个请求中发送其 schema。工具列表授予 read 但省略 write 的会话通过仅写传输挂载设备（文件系统写入仍被拒绝）",
	"setting.tools.xdevDocs.label": "xd:// 提示文档",
	"setting.tools.xdevDocs.description":
		"选择在系统提示中内联哪些已挂载设备文档和 schema。Built-ins 仅核心工具内联，MCP 和扩展工具按需获取",
	"setting.tools.xdevInlineDevices.label": "xd:// 内联设备",
	"setting.tools.xdevInlineDevices.description":
		"当 xd:// 提示文档 为 Built-ins Only 时，匹配这些 glob 模式的动态设备内联（如 mcp__context_mode_*）。Catalog Only 忽略此设置",
	"setting.mcp.enableProjectConfig.label": "MCP 项目配置",
	"setting.mcp.enableProjectConfig.description": "从项目根目录加载 .mcp.json/mcp.json",
	"setting.mcp.renderMarkdownResults.label": "MCP Markdown 结果",
	"setting.mcp.renderMarkdownResults.description": "在转录中非 JSON MCP 文本结果渲染为 Markdown",
	"setting.mcp.notifications.label": "MCP 更新注入",
	"setting.mcp.notifications.description": "将 MCP 资源更新注入 agent 对话",
	"setting.mcp.notificationDebounceMs.label": "MCP 通知去抖",
	"setting.mcp.notificationDebounceMs.description": "MCP 资源更新注入对话前的去抖窗口（毫秒）",
	"setting.tasks.todoClearDelay.label": "任务清单自动清除延迟",
	"setting.tasks.todoClearDelay.description": "已完成或放弃的任务清单项从任务清单小部件中移除前的延迟",
	"setting.extensionHandlers.toolCallTimeoutMs.label": "工具调用处理器超时（毫秒）",
	"setting.extensionHandlers.toolCallTimeoutMs.description":
		"扩展 tool_call 处理器的正有限活跃工作超时；无效值使用 30000ms，等待 OMP 拥有的对话框的时间不计入",
	"setting.dev.autoqa.label": "自动 QA",
	"setting.dev.autoqa.description":
		"自动化工具问题报告（xd://report_issue）。默认开启；首次报告要求同意，拒绝后直到显式重新启用才关闭报告",
	"setting.dev.autoqaPush.endpoint.label": "自动 QA 推送端点",
	"setting.dev.autoqaPush.endpoint.description":
		"接收自动 QA JSON 报告的完整 URL（默认 https://qa.omp.sh/v1/grievances）",
};

export default strings;
